<?xml version="1.0" encoding="utf-8"?><Database Name="GeoLabOnlinedb" Class="GeolabOnlineDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\fido;Initial Catalog=GeoLabOnlinedb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GeoLabOnlinedbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="User_UserCode" Member="UserCodes" ThisKey="ID" OtherKey="UserId" Type="UserCode" />
      <Association Name="User_UserCurse" Member="UserCurses" ThisKey="ID" OtherKey="UserId" Type="UserCurse" />
      <Association Name="User_UserLesson" Member="UserLessons" ThisKey="ID" OtherKey="UserId" Type="UserLesson" />
      <Association Name="User_UserNote" Member="UserNotes" ThisKey="ID" OtherKey="UserId" Type="UserNote" />
      <Association Name="User_UserQuiz" Member="UserQuizs" ThisKey="ID" OtherKey="UserId" Type="UserQuiz" />
    </Type>
  </Table>
  <Table Name="dbo.LessonQuiz" Member="LessonQuizs">
    <Type Name="LessonQuiz">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="LessonQuiz_LessonQuizAnswer" Member="LessonQuizAnswers" ThisKey="ID" OtherKey="QuizId" Type="LessonQuizAnswer" />
      <Association Name="LessonQuiz_UserQuiz" Member="UserQuizs" ThisKey="ID" OtherKey="QuizId" Type="UserQuiz" />
      <Association Name="Lesson_LessonQuiz" Member="Lesson" ThisKey="LessonId" OtherKey="ID" Type="Lesson" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonQuizAnswers" Member="LessonQuizAnswers">
    <Type Name="LessonQuizAnswer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Correct" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="QuizId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonQuizAnswer_UserQuiz" Member="UserQuizs" ThisKey="ID" OtherKey="AnswerID" Type="UserQuiz" />
      <Association Name="LessonQuiz_LessonQuizAnswer" Member="LessonQuiz" ThisKey="QuizId" OtherKey="ID" Type="LessonQuiz" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lessons" Member="Lessons">
    <Type Name="Lesson">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonsTitel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LessonsDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LessonsVideoLink" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CodeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LessonsLvl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lesson_LessonQuiz" Member="LessonQuizs" ThisKey="ID" OtherKey="LessonId" Type="LessonQuiz" />
      <Association Name="Lesson_UserCode" Member="UserCodes" ThisKey="ID" OtherKey="LessonId" Type="UserCode" />
      <Association Name="Lesson_UserLesson" Member="UserLessons" ThisKey="ID" OtherKey="LessonsId" Type="UserLesson" />
      <Association Name="Lesson_UserNote" Member="UserNotes" ThisKey="ID" OtherKey="LessonsId" Type="UserNote" />
      <Association Name="LessonsCodeType_Lesson" Member="LessonsCodeType" ThisKey="CodeType" OtherKey="ID" Type="LessonsCodeType" IsForeignKey="true" />
      <Association Name="Subject_Lesson" Member="Subject" ThisKey="SubjectId" OtherKey="ID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonsCodeType" Member="LessonsCodeTypes">
    <Type Name="LessonsCodeType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SourceType" Type="System.Data.Linq.Binary" DbType="VarBinary(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="source" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LessonsCodeType_Lesson" Member="Lessons" ThisKey="ID" OtherKey="CodeType" Type="Lesson" />
    </Type>
  </Table>
  <Table Name="dbo.UserCodes" Member="UserCodes">
    <Type Name="UserCode">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lesson_UserCode" Member="Lesson" ThisKey="LessonId" OtherKey="ID" Type="Lesson" IsForeignKey="true" />
      <Association Name="User_UserCode" Member="User" ThisKey="UserId" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserCurse" Member="UserCurses">
    <Type Name="UserCurse">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_UserCurse" Member="User" ThisKey="UserId" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="Subject_UserCurse" Member="Subject" ThisKey="SubjectId" OtherKey="ID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLessons" Member="UserLessons">
    <Type Name="UserLesson">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonsStatus" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Lesson_UserLesson" Member="Lesson" ThisKey="LessonsId" OtherKey="ID" Type="Lesson" IsForeignKey="true" />
      <Association Name="User_UserLesson" Member="User" ThisKey="UserId" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserNotes" Member="UserNotes">
    <Type Name="UserNote">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoteText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lesson_UserNote" Member="Lesson" ThisKey="LessonsId" OtherKey="ID" Type="Lesson" IsForeignKey="true" />
      <Association Name="User_UserNote" Member="User" ThisKey="UserId" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserQuiz" Member="UserQuizs">
    <Type Name="UserQuiz">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuizId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="LessonQuiz_UserQuiz" Member="LessonQuiz" ThisKey="QuizId" OtherKey="ID" Type="LessonQuiz" IsForeignKey="true" />
      <Association Name="LessonQuizAnswer_UserQuiz" Member="LessonQuizAnswer" ThisKey="AnswerID" OtherKey="ID" Type="LessonQuizAnswer" IsForeignKey="true" />
      <Association Name="User_UserQuiz" Member="User" ThisKey="UserId" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CourseSubject" Member="CourseSubjects">
    <Type Name="CourseSubject">
      <Column Name="courseSubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Subject_CourseSubject" Member="Subject" ThisKey="SubjectID" OtherKey="ID" Type="Subject" IsForeignKey="true" />
      <Association Name="Course_CourseSubject" Member="Course" ThisKey="CourseID" OtherKey="ID" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectTitle" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubjectDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SubjectVideoLink" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Subject_Lesson" Member="Lessons" ThisKey="ID" OtherKey="SubjectId" Type="Lesson" />
      <Association Name="Subject_UserCurse" Member="UserCurses" ThisKey="ID" OtherKey="SubjectId" Type="UserCurse" />
      <Association Name="Subject_CourseSubject" Member="CourseSubjects" ThisKey="ID" OtherKey="SubjectID" Type="CourseSubject" />
      <Association Name="Subject_Lecture" Member="Lectures" ThisKey="ID" OtherKey="UserSubject" Type="Lecture" />
    </Type>
  </Table>
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseTitle" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CourseDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CourseVideoLink" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DirectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_CourseSubject" Member="CourseSubjects" ThisKey="ID" OtherKey="CourseID" Type="CourseSubject" />
      <Association Name="Direction_Course" Member="Direction" ThisKey="DirectionId" OtherKey="ID" Type="Direction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Direction" Member="Directions">
    <Type Name="Direction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DirectionTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DirectionDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DirectionImage" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DirectionImageExt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DirectionDescMini" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Direction_Course" Member="Courses" ThisKey="ID" OtherKey="DirectionId" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Lecture" Member="Lectures">
    <Type Name="Lecture">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserBio" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserMail" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="UserPhoto" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="UserSubject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserSubjectName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Subject_Lecture" Member="Subject" ThisKey="UserSubject" OtherKey="ID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
</Database>